### PR TITLE
Solution struct

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31)

### CODE REVIEW

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @AlexandreAmice)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 131 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFimS_-XyQ3PPUfeqT:-MvFimSa3OY1FmK9LYWy:b-i1xfeo) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L131)):*
> ```cpp
>   py::class_<multibody::SeparatingPlane>(
>       m, "SeparatingPlane", doc.SeparatingPlane.doc)
>       .def("a",
> ```

Better to use 
```cc
def_readonly("a", &SeparatingPlane::a, py_rvp::copy, doc.SeparatingPlane.a.doc)
```
here. `a` is a data in the C++ class, by using a lambda function, we change it from a data to a function, the users will need to call it as `plane.a()` in python, while in C++ the user call it as `plane.a`, causing inconsistency.
___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 146 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFj8fF6cXZ5GU1LHMT:-MvFj8fG5jlot-1gtP0F:bs4q9op) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L146)):*
> ```cpp
>       .def_readonly(
>           "order", &SeparatingPlane::order, doc.SeparatingPlane.order.doc)
>       .def("decision_variables",
> ```

Ditto.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 92 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFdxEy4VlegYyoX3I2:-MvFdxEy4VlegYyoX3I3:b-all7j7) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L92)):*
> ```objc
> struct CspaceFreeRegionSolution{
> //   public:
> //    DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN(CspaceFreeRegionSolution)
> ```

I think you can un-comment this and the next line? And remove `CspaceFreeRegionSolutio() {}`?
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 96 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFe8fy8aENKWAEJZlp:-MvFe8fy8aENKWAEJZlq:b-ewt7g6) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L96)):*
> ```objc
>    CspaceFreeRegionSolution() {}
>    CspaceFreeRegionSolution(
>      Eigen::Ref<Eigen::MatrixXd> m_C,
> ```

I think here it is better to use `Eigen::MatrixXd` instead of `Eigen::Ref<Eigen::MatrixXd>`.

If you want to pass in a const reference to an Eigen matrix, then it is better to use `const Eigen::Ref<const Eigen::MatrixXd>`. But here since you use the move-semantic in the constructor, then it is better to pass-by-value directly.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 116 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFeWUR-XEu0O6wntKp:-MvFeWUR-XEu0O6wntKq:b-3wfutv) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L116)):*
> ```objc
> //
>    CspaceFreeRegionSolution(
>      Eigen::Ref<Eigen::MatrixXd> m_C,
> ```

Ditto on the input type, use `Eigen::MatrixXd` directly.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 135 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFerxh7gD5rdvbZW_f:-MvFerxh7gD5rdvbZW_g:b-ovewgn) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L135)):*
> ```objc
> 
>    // values defining Inscribed ellipsoid {t | t = Ps + q , norm(s) <= 1}
>    Eigen::MatrixXd P;
> ```

I would suggest to use `std::optional<Eigen::MatrixXd> P, std::optional<Eigen::VectorXd> q` here. 

In the bisection, we don't need to search for the inscribed ellipsoid, hence P and q would contain garbage values, but when the users access P and q, he/she doesn't know if it contains garbage. On the other hand, by using std::optional, the user knows whether P and q is garbage (by default std::optional is set as std::nullopt, indicating garbage value).
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 532 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFfh9a8FCp0EimO7No:-MvFfh9a8FCp0EimO7Np:b2gcukx) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L532)):*
> ```objc
>     // The objective function used in maximizing the volume of the inscribed
>     // ellipsoid.
>     EllipsoidVolume ellipsoid_volume{EllipsoidVolume::kNthRoot};
> ```

Do we always find the inscribed ellipsoid in bisection? If not, I would suggest to use std::optional<EllipsoidVolume> here, where an empty ellipsoid_volume suggests don't search for the inscribed ellipsoid.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1568 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFgZHC5uIXLBV_43IX:-MvFgZHC5uIXLBV_43IY:bvnccp7) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1568)):*
> ```cpp
>       (cspace_free_region_solution->separating_planes) =
>           GetSeparatingPlanesSolution(*this, is_plane_active, result_polytope);
>       FindLargestInscribedEllipsoid(
> ```

Why finding the inscribed ellipsoid here again? This FindLargestInscribedEllipsoid is called when the solver fails to find the polytope C*t<=d. Do we want to find the inscribed ellipsoid even when it cannot find the polytope?
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1608 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFh-YB7IaZ_SvhofqZ:-MvFh-YB7IaZ_Svhofq_:b8eneoo) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1608)):*
> ```cpp
>     (cspace_free_region_solution->separating_planes) =
>         GetSeparatingPlanesSolution(*this, is_plane_active, result_polytope);
>     FindLargestInscribedEllipsoid(
> ```

Why finding the largest ellipsoid here? I would think that the next "Lagrangian step" will find the ellipsoid anyway?

The only case I can think that we need to find the ellpsoid is that this is the last iteration of the bilinear alternation, hence there won't be next "Lagrangian step". In that case, we should move this `FindLargestInscribedEllipsoid` outside of the while loop, just before this function CspacePolytopeBilinearAlternation exits.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1679 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFi41Z1Bkd9Ix1P895:-MvFi41Z1Bkd9Ix1P896:bgcorcb) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1679)):*
> ```cpp
>        &d_max, &is_plane_active, &separating_plane_to_tuples,
>        cspace_free_region_solution](const Eigen::VectorXd& d, bool search_d,
>                               bool compute_polytope_volume, bool verbose,
> ```

As you capture `binary_search_option` in this lambda function, it is better to remove `search_d, compute_polytope_volume, verbose, multi_thread` from the input of this lambda function, but use their value in `binary_search_option`.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1695 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFhu5eBUFRGssQRgJg:-MvFhu5eBUFRGssQRgJh:b-3an4tv) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1695)):*
> ```cpp
>         if (is_success) {
>           (cspace_free_region_solution->d) = d;
>           FindLargestInscribedEllipsoid(
> ```

It's unclear to me why we need to search the inscribed ellipsoid in the bisection.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 131 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFimS_-XyQ3PPUfeqT:-MvGAewF2DQUwyNj74FJ:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L131)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Better to use 
```cc
def_readonly("a", &SeparatingPlane::a, py_rvp::copy, doc.SeparatingPlane.a.doc)
```
here. `a` is a data in the C++ class, by using a lambda function, we change it from a data to a function, the users will need to call it as `plane.a()` in python, while in C++ the user call it as `plane.a`, causing inconsistency.
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 146 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFj8fF6cXZ5GU1LHMT:-MvGAegE-LUZ60JJKJEj:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L146)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 96 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFe8fy8aENKWAEJZlp:-MvGB7IC-8N-n3fYM1ds:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L96)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think here it is better to use `Eigen::MatrixXd` instead of `Eigen::Ref<Eigen::MatrixXd>`.

If you want to pass in a const reference to an Eigen matrix, then it is better to use `const Eigen::Ref<const Eigen::MatrixXd>`. But here since you use the move-semantic in the constructor, then it is better to pass-by-value directly.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 116 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFeWUR-XEu0O6wntKp:-MvGB7b6DTHP3RhX8bn5:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L116)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto on the input type, use `Eigen::MatrixXd` directly.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 135 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFerxh7gD5rdvbZW_f:-MvGBKGNDRLoTczRx58K:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L135)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I would suggest to use `std::optional<Eigen::MatrixXd> P, std::optional<Eigen::VectorXd> q` here. 

In the bisection, we don't need to search for the inscribed ellipsoid, hence P and q would contain garbage values, but when the users access P and q, he/she doesn't know if it contains garbage. On the other hand, by using std::optional, the user knows whether P and q is garbage (by default std::optional is set as std::nullopt, indicating garbage value).
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 532 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFfh9a8FCp0EimO7No:-MvGBeXz4H-56YL8m4_9:biau9ee) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L532)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do we always find the inscribed ellipsoid in bisection? If not, I would suggest to use std::optional<EllipsoidVolume> here, where an empty ellipsoid_volume suggests don't search for the inscribed ellipsoid.
</blockquote></details>

I would prefer to be consistent in that when searching for planes you always return the inscribed ellipsoid volume. That way the user always has the full info from the program
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1568 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFgZHC5uIXLBV_43IX:-MvGC86T5V314ZWX6mYz:b9jozqv) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1568)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why finding the inscribed ellipsoid here again? This FindLargestInscribedEllipsoid is called when the solver fails to find the polytope C*t<=d. Do we want to find the inscribed ellipsoid even when it cannot find the polytope?
</blockquote></details>

remove this search plus the GetSeparatingPlaneSolution call
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1608 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFh-YB7IaZ_SvhofqZ:-MvGEFU5BFh3eJZbXcZR:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1608)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why finding the largest ellipsoid here? I would think that the next "Lagrangian step" will find the ellipsoid anyway?

The only case I can think that we need to find the ellpsoid is that this is the last iteration of the bilinear alternation, hence there won't be next "Lagrangian step". In that case, we should move this `FindLargestInscribedEllipsoid` outside of the while loop, just before this function CspacePolytopeBilinearAlternation exits.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1679 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFi41Z1Bkd9Ix1P895:-MvGEx08-6fI7V-5T5G5:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1679)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

As you capture `binary_search_option` in this lambda function, it is better to remove `search_d, compute_polytope_volume, verbose, multi_thread` from the input of this lambda function, but use their value in `binary_search_option`.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1695 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFhu5eBUFRGssQRgJg:-MvGEyCD3-nG7Z5fRmxw:b8dbog2) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.cc#L1695)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It's unclear to me why we need to search the inscribed ellipsoid in the bisection.
</blockquote></details>

For consistency of the output struct. It is nice for the return of any certification step to always give an idea of the volume of the return.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31)* status: all files reviewed (commit messages unreviewed), 11 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 92 at r1](https://reviewable.io/reviews/alexandreamice/drake/31#-MvFdxEy4VlegYyoX3I2:-MvGH6hU3A-Nbn2uFZVy:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f495a47ca0f13552e8b48701319b27cf1d56c105/multibody/rational_forward_kinematics/cspace_free_region.h#L92)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think you can un-comment this and the next line? And remove `CspaceFreeRegionSolutio() {}`?
</blockquote></details>

Done.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice and @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 132 at r2](https://reviewable.io/reviews/alexandreamice/drake/31#-MvGiDar6cOIRtVW9Qj-:-MvGiDar6cOIRtVW9Qj0:b-mfku0s) ([raw file](https://github.com/alexandreamice/drake/blob/2f6dc758084b6f87652cd9e4934af9426cfdff04/multibody/rational_forward_kinematics/cspace_free_region.h#L132)):*
> ```objc
> 
>    // values defining Inscribed ellipsoid {t | t = Ps + q , norm(s) <= 1}
>    std::optional<Eigen::MatrixXd> P;
> ```

Sorry for being pedantic. Now that we always compute P and q, I think it is better to remove std::optional, which makes the code easier (without checking P.has_value()).

**Review by hongkai-dai — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/31#-:-MvHNdrD4YBRxl-pM4bW:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
