### PR TITLE
add in extra ComputeTValue and ComputeQValue with their bindings

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38)

### CODE REVIEW

**Review by hongkai-dai — APPROVED** [review]
Could you also add the unit test in this PR, that if we call ComputeQValue(ComputeTValue(q)) we get back q? Also if we call ComputeTValue(ComputeQValue(t)) we get back t.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38#-:-MwmL8Yw0GLz-bxNU0uN:b-eh3ylk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38#-:-MwmdKOA2tHnJTs5rsOU:bb6un1j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by hongkai-dai — APPROVED** [review]
Sorry I don't see the change in the unit test yet. Have you pushed it?

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38#-:-MwmkdLeEC7hGlWvzGmk:b-jjg1z1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — COMMENTED** [review]
Pushed it to the wrong branch initially. Should be good to go

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38#-:-MwmnCiE02K0cIIyE8oN:b-ja1qod)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/38#-:-MwmouZR9NoZs7UH5T_U:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
