### PR TITLE
Partition the IRIS polytope to boxes.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16#-:-Mu-3TCSDh8jusB5BHFV:b-kengf8)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[geometry/optimization/polytope_cover.cc, line 127 at r1](https://reviewable.io/reviews/alexandreamice/drake/16#-MuBLgY9AY0VZv4ULg1A:-MuBLgY9AY0VZv4ULg1B:b-agxtys) ([raw file](https://github.com/alexandreamice/drake/blob/c88bfc3b6d0a91530001c65c2d5db4d25bbd542e/geometry/optimization/polytope_cover.cc#L127)):*
> ```cpp
>     // b(2i) = 1 implies box_lo(i) >= obstacle.up(i).
>     // We write box_lo(i) >= outer_box.lo(i) + (obstale.up(i) - outer_box.lo(i))
>     // * b(2i)
> ```

mispelled obstacle in the comment
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1517 at r1](https://reviewable.io/reviews/alexandreamice/drake/16#-MuBNOUE6kRf3bKu4keS:-MuBNOUE6kRf3bKu4keT:b-i5n60w) ([raw file](https://github.com/alexandreamice/drake/blob/c88bfc3b6d0a91530001c65c2d5db4d25bbd542e/multibody/rational_forward_kinematics/cspace_free_region.cc#L1517)):*
> ```cpp
> }
> 
> double FindEpsilonLower(const Eigen::Ref<const Eigen::MatrixXd>& C,
> ```

This functions find the minimal uniform shrinkage. Could you add a TODO for me to implement my version which searches for each inequality independently?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[geometry/optimization/polytope_cover.cc, line 127 at r1](https://reviewable.io/reviews/alexandreamice/drake/16#-MuBLgY9AY0VZv4ULg1A:-MuEDgvN6FAL3LLz1lXA:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/c88bfc3b6d0a91530001c65c2d5db4d25bbd542e/geometry/optimization/polytope_cover.cc#L127)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

mispelled obstacle in the comment
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1517 at r1](https://reviewable.io/reviews/alexandreamice/drake/16#-MuBNOUE6kRf3bKu4keS:-MuEDiuR0R-zZu3J7XXd:bpf60tw) ([raw file](https://github.com/alexandreamice/drake/blob/c88bfc3b6d0a91530001c65c2d5db4d25bbd542e/multibody/rational_forward_kinematics/cspace_free_region.cc#L1517)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This functions find the minimal uniform shrinkage. Could you add a TODO for me to implement my version which searches for each inequality independently?
</blockquote></details>

Done. This has been added in the upstream through another PR.

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 473 at r2](https://reviewable.io/reviews/alexandreamice/drake/16#-MuGXpOqDMH3RvoXOIXI:-MuGXpOqDMH3RvoXOIXJ:bel1oop) ([raw file](https://github.com/alexandreamice/drake/blob/ed8ef4b8f25d44c6cec2142de366f40e6ac32945/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L473)):*
> ```cpp
>           py::arg("tighten"), doc.FindRedundantInequalities.doc)
>       .def("FindEpsilonLower", &FindEpsilonLower, py::arg("C"), py::arg("d"),
>           py::arg("t_lower"), py::arg("t_upper"), py::arg("t_inner_pts"),
> ```

t_inner_pts and inner_polytope are optional arguments so it would be more pythonic to have default arguments for them

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 473 at r2](https://reviewable.io/reviews/alexandreamice/drake/16#-MuGXpOqDMH3RvoXOIXI:-MuHNP1X0gb76rdHybME:b-jd3glb) ([raw file](https://github.com/alexandreamice/drake/blob/ed8ef4b8f25d44c6cec2142de366f40e6ac32945/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L473)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

t_inner_pts and inner_polytope are optional arguments so it would be more pythonic to have default arguments for them
</blockquote></details>

Done. TIL pythonic prefers having default arguments. In C++ it's the other way, that google style guide doesn't like default arguments.

**Review by AlexandreAmice — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
