### PR TITLE
templatize SeparatingPlane.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Write separating plane to txt file as well.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)

### CODE REVIEW

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)* status: all files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 112 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0C8Sa0eqwsDEnMz43:-N-0C8Sa0eqwsDEnMz44:bfemmwl) ([raw file](https://github.com/alexandreamice/drake/blob/7090690737799cadbe453962b5baab528b338e03/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L112)):*
> ```cpp
>   }  // RationalForwardKinematics Util methods
> 
>   //  type_visit([m](auto dummy) { DoPoseDeclaration(m, dummy); },
> ```

We should remove this comment as well
___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 543 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0DDx32jVgqqbvVLeL:-N-0DDx32jVgqqbvVLeM:b-3tok30) ([raw file](https://github.com/alexandreamice/drake/blob/7090690737799cadbe453962b5baab528b338e03/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L543)):*
> ```cpp
>       "ReadCspacePolytopeFromFile",
>       [](const std::string& filename) {
>         Eigen::MatrixXd C;
> ```

Did you mean to remove this?
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 113 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0Dm5HEEptAxrBxTOG:-N-0Dm5HEEptAxrBxTOH:byj2syc) ([raw file](https://github.com/alexandreamice/drake/blob/ae85013cef95826ec924339aaa5ecc9093fc5cc0/multibody/rational_forward_kinematics/cspace_free_region.h#L113)):*
> ```objc
>   }
> }
> ```

Shouldn't we put some sort of catch here to ensure that something sensible happens in the function if none of the switch cases are met. For now, I understand that this is an exhaustive list of supported SeparatingPlaneOrders, but it may not be in the future.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 881 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0EDn63VR78hrnXuPd:-N-0EDn63VR78hrnXuPe:b-n7yu98) ([raw file](https://github.com/alexandreamice/drake/blob/ae85013cef95826ec924339aaa5ecc9093fc5cc0/multibody/rational_forward_kinematics/cspace_free_region.h#L881)):*
> ```objc
>                        std::pair<BodyIndex, Eigen::VectorXd>>*
>         separating_planes);
> ```

Are there pre-conditions on the plant and inspector here? If so can you document them.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)* status: all files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 543 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0DDx32jVgqqbvVLeL:-N-0nVNz7oBx9FuvT1XX:b-tryhzl) ([raw file](https://github.com/alexandreamice/drake/blob/7090690737799cadbe453962b5baab528b338e03/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L543)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Did you mean to remove this?
</blockquote></details>

Do you mean the function `CalcCspacePolytopeVolume`? Why removing it?
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 113 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0Dm5HEEptAxrBxTOG:-N-0nqLo0v51p7Ow7P02:b-3gexv4) ([raw file](https://github.com/alexandreamice/drake/blob/ae85013cef95826ec924339aaa5ecc9093fc5cc0/multibody/rational_forward_kinematics/cspace_free_region.h#L113)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Shouldn't we put some sort of catch here to ensure that something sensible happens in the function if none of the switch cases are met. For now, I understand that this is an exhaustive list of supported SeparatingPlaneOrders, but it may not be in the future.
</blockquote></details>

The compiler will complain if `switch` misses a case.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 881 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0EDn63VR78hrnXuPd:-N-0oJHW-LZO_uFoYGTF:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/ae85013cef95826ec924339aaa5ecc9093fc5cc0/multibody/rational_forward_kinematics/cspace_free_region.h#L881)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Are there pre-conditions on the plant and inspector here? If so can you document them.
</blockquote></details>

Done.

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 543 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0DDx32jVgqqbvVLeL:-N-3ACHAD8uWe2Jtto0C:b-ltg6wq) ([raw file](https://github.com/alexandreamice/drake/blob/7090690737799cadbe453962b5baab528b338e03/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L543)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you mean the function `CalcCspacePolytopeVolume`? Why removing it?
</blockquote></details>

The bindings for WriteCspacePolytopeToFile and ReadCspacePolytopeFromFile have been removed.

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 543 at r1](https://reviewable.io/reviews/alexandreamice/drake/40#-N-0DDx32jVgqqbvVLeL:-N-OFXRC5TF2jAT82ZoZ:bojn6u8) ([raw file](https://github.com/alexandreamice/drake/blob/7090690737799cadbe453962b5baab528b338e03/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L543)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

The bindings for WriteCspacePolytopeToFile and ReadCspacePolytopeFromFile have been removed.
</blockquote></details>

`Write/ReadCspacePolytopeFromFile` works for C++ as it stores the numeric values to a txt file. In Python it makes more sense to store the data directly as a numpy file, hence I removed their python binding.

CalcCspacePolytopeVolume works in both C++ and python and I think we should keep it here.

**Review by AlexandreAmice — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
