### PR TITLE
C iris rational forward kinematics cleanup

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39)

### CODE REVIEW

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 69 of 97 files at r1.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39)* status: 69 of 97 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice and @hongkai-dai)

___
*[multibody/rational_forward_kinematics/test/iiwa_shelf_demo.cc, line 102 at r1](https://reviewable.io/reviews/alexandreamice/drake/39#-MwovjOl5RujuGugp_71:-MwovjOl5RujuGugp_72:bve656g) ([raw file](https://github.com/alexandreamice/drake/blob/1b2121d8f34fa5e29b4026f65efbafabb80c267f/multibody/rational_forward_kinematics/test/iiwa_shelf_demo.cc#L102)):*
> ```cpp
> 
>     const std::string shelf_file_path =
>         FindResourceOrThrow("drake/sos_iris_certifier/shelves.sdf");
> ```

This is where currently shelves.sdf is used.
___
*[sandbox/shelves.sdf, line 0 at r1](https://reviewable.io/reviews/alexandreamice/drake/39#-Mwov6g01228pD5pabDg:-Mwov6g1CCI7uETpsCdJ:b-cv3mwe) ([raw file](https://github.com/alexandreamice/drake/blob/1b2121d8f34fa5e29b4026f65efbafabb80c267f/sandbox/shelves.sdf#L0)):*
BTW, this file is used in multibody/rational_forward_kinematics/test/iiwa_shelf_demo.cc.
I would suggest to move this file to multibody/rationalforward_kinematics/test folder, and modify the sdf file path in iiwa_shelf_demo.cc.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39)* status: 68 of 98 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/test/iiwa_shelf_demo.cc, line 102 at r1](https://reviewable.io/reviews/alexandreamice/drake/39#-MwovjOl5RujuGugp_71:-N-0AJoAAFb51DWuNQ24:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/1b2121d8f34fa5e29b4026f65efbafabb80c267f/multibody/rational_forward_kinematics/test/iiwa_shelf_demo.cc#L102)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This is where currently shelves.sdf is used.
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 97 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39#-:-N-0Xc9Y4b0vSoAwNO2t:bg7igkv)* status: 72 of 98 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 8 of 97 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39)* status: 80 of 98 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 18 of 97 files at r1.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/39)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
