### PR TITLE
Handle sphere and capsule collision geometries.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Also introduce CollisionGeometry class in place of ConvexGeometry class.
The user can set separating_plane_delta for a pair of polytopic collision geometries.

This PR only introduces sphere/cylindrical/capsule collision geometry with a constant order separating plane (namely the separating plane normal `n` and `d` doesn't change as the robot configuration changes). Hence the collision avoidance constraint introduces second order cone constraints. In the next PR I will introduce the feature to handle `n` and `d` being affine function of `t`, and will bring in matrix-sos constraint into the formulation.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50#-:-N7N_IBw-w4ZgU3nzai_:b-kengf8)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
This is an enormous PR thanks for writing all of this. One overall comment is that I am not sure I understand the change to from $1$ to $\delta$. Is $\delta$ a new hyperparameter when using sphere and capsule collisions? Why don't we optimize for it?

Also, we should consider linking this implementation to some document explaining the program as it is so large that at this point it is absolutely incomprehensible if you haven't spent a few months working on it.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50#-:-N7pkhXf3AX5OZ_qsrd4:brrw173)* status: all files reviewed, 14 unresolved discussions (waiting on @hongkai-dai)

___
*[`bindings/pydrake/multibody/rational_forward_kinematics_py.cc` line 156 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pmvC78EgKcz-LrBAz:-N7pmvC8EI93ZdJ87JzQ:bc0814c) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L156)):*
> ```cpp
>           doc.CollisionGeometryType.kPolytope.doc)
>       .value("kSphere", multibody::CollisionGeometryType::kSphere,
>           doc.CollisionGeometryType.kSphere.doc);
> ```

Missing the "kCapsule"
___
*[`bindings/pydrake/multibody/rational_forward_kinematics_py.cc` line 320 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pnK2S8DCjpfm6YznH:-N7pnK2S8DCjpfm6YznI:b-6mlve8) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L320)):*
> ```cpp
> 
>   cspace_cls
>       .def("map_collisions_to_separating_planes",
> ```

As noted later, consider renaming this to `map_geometries_to_separating_planes` or something similar
___
*[`multibody/rational_forward_kinematics/collision_geometry.h` line 22 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pYWhA9lSeoAh4sKzQ:-N7pYWhA9lSeoAh4sKzR:boly0s3) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.h#L22)):*
> ```objc
> class CollisionGeometry {
>  public:
>   DRAKE_NO_COPY_NO_MOVE_NO_ASSIGN(CollisionGeometry)
> ```

Why no copy no move and no assign?
___
*[`multibody/rational_forward_kinematics/collision_geometry.h` line 49 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pYxkt6zvTro-Ok3Hx:-N7pYxkt6zvTro-Ok3Hy:b-ooioei) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.h#L49)):*
> ```objc
> };
> 
> Eigen::Matrix3Xd GetVertices(const geometry::Shape& shape);
> ```

Could you add some documentation on this method? It makes a lot of sense for polytopes but I'm not sure I understand the expected behavior for other convex shapes. 
___
*[`multibody/rational_forward_kinematics/collision_geometry.cc` line 35 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pZFLA8WDunmuyXBG7:-N7pZFLA8WDunmuyXBG8:b-5e5573) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.cc#L35)):*
> ```cpp
>     vertices.row(2) *= box->height() / 2;
>     return vertices;
>   } else if (dynamic_cast<const geometry::Convex*>(&shape) != nullptr) {
> ```

I am not sure I understand this implementation. Some extra comments may help as would documentation in the header file
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 42 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pZUr03klj5q3fS9HF:-N7pZUr03klj5q3fS9HG:b3x3sx0) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L42)):*
> ```objc
> /**
>  * One collision geometry is on the "positive" side of the separating plane,
>  * namely {x| aᵀx + b ≥ δ}, and the other collision geometry is on the
> ```

add `\delta \geq 0` to documentation
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 205 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7p_26_0rTR949sOuju:-N7p_26_0rTR949sOujv:b-uko8fb) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L205)):*
> ```objc
>          expressed_body_index{m_expressed_body_index},
>          other_side_link_geometry{m_other_side_link_geometry},
>          a_A{std::move(m_a_A)},
> ```

We  may want to document why we call this a_A. I.e. explain the purpose of the expressed in link in the documentation.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 278 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pXS6o2BaV4rnj1PYy:-N7pXS6o2BaV4rnj1PYz:b-z5pmzx) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L278)):*
> ```objc
>    */
>   const std::unordered_map<SortedPair<geometry::GeometryId>, int>&
>   map_collisions_to_separating_planes() const {
> ```

I think this would make more sense to call map_geometries_to_separating_planes
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 289 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pdYip6Vg73nwj49la:-N7pdYip6Vg73nwj49lb:b-exlxly) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L289)):*
> ```objc
>    * filtered_collision_pair.
>    */
>   std::vector<LinkOnPlaneSideRational> GenerateLinkOnOneSideOfPlaneRationals(
> ```

Can we change this to `GenerateRationalsForLinkOnOneSideOfPlane`. It would be more grammatically correct?



_Code quote:_
```objc
GenerateLinkOnOneSideOfPlaneRationals
```
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 963 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pbM117JLhnWFDFi_k:-N7pbM117JLhnWFDFi_l:b-nn0l62) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L963)):*
> ```objc
>     const solvers::MathematicalProgramResult& result);
> 
> /**In bilinear alternation, each conic program (with a linear cost) finds an
> ```

nit: comment style
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 263 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pbVg_0gl8S8mfTwuC:-N7pbVg_0gl8S8mfTwuD:bxi71xp) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L263)):*
> ```cpp
>       scene_graph_{scene_graph},
>       link_geometries_{GetCollisionGeometries(diagram, plant, scene_graph)},
>       plane_order_for_polytope_{plane_order},
> ```

perhaps we don't specify "for_polytope" here and just leave in the documentation that plane_order_ only works for polytopes. Regardless I think this name as written may be somewhat confusing.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 1786 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pfTV6-yg6dFUYrROq:-N7pfTV73p2kenb0QF8d:b-w74s5e) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L1786)):*
> ```cpp
>   // Checks if C*t<=d, t_lower<=t<=t_upper is collision free.
>   // This function will update d_sol when the polytope is collision free.
>   auto is_polytope_collision_free =
> ```

This lambda is getting to be quite large. Should we move it to its own stand-alone private method? Or at least break extract the is_success clause into its own lambda or method.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 1978 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pj052AjcRv2IgMy-L:-N7pj05B7232tFTdlteg:b-kj8i02) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L1978)):*
> ```cpp
>   const symbolic::Polynomial b_poly({{monomial_one, b}});
> 
>   // Compute the rational for a.dot(p_AQ)+b-offset on the positive side, and
> ```

What is p_AQ
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2011 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pj6JU7LQ7CL6y8Qo9:-N7pj6KbCCpkQBTi_zB8:b-bhddfg) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L2011)):*
> ```cpp
>       // TODO(hongkai.dai): cache the map from geometry_id to vertices since
>       // getting the vertices might be expensive.
>       const Eigen::Matrix3Xd p_BV =
> ```

Maybe add documentation explaining that we compute the rational for every polytope vertex to be consistent with the other two cases.

**Review by hongkai-dai — COMMENTED** [review]
There several reasons to introduce `delta` in place of `1`.
1. We use the separating plane a^Tx + b >= 1 in the polytopic case, instead of a^Tx + b >= 0, because the latter formulation allows the degenerate case a = b = 0. On the other hand, for sphere / cylinder / capsule cases there is no need to use `1` to avoid the degenerate solution. Now we have a.dot(sphere_center) + b >= radius, |a| <= 1. The fact that radius is a strict positive number already prevents the degenerate solution a = b = 0. Hence you can see that for different geometries the right hand side of the separating plane condition is different, and we introduce this `delta` to handle different cases.
2. Even for the polytopic collision geometry, later we will try to maximize the separating distance, and the formulation will become a^Tx + b >= ε, |a|<=1, a.dot(c) + b >= r where ε is the separating distance, `c` is a point in the strict interior of the polytope, and `r` is the distance from `c` to the surface of the polytope. The condition  a.dot(c) + b >= r prevents the degenerate solution a = b = 0. Notice that here we don't need `1` either.
3. I was just curious if some of the numerical problems are due to using `1` in the right-hand side. By setting the right-hand side of the separating plane condition to 1, then for two geometries that are almost in contact with each other but slightly separated, we will need very large value of `a` and `b` to separate them. This large value of `a` and `b` might cause numerical issue in Mosek. In my experiment, sometimes by changing `1` to `0.1` or `0.01` it helps the numerical issue, sometimes it doesn't. So this is an experiment.

I will add the latex file that generates the formulation.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50#-:-N7qFpUF31QoZRfL_g7m:b-h7iwt8)* status: all files reviewed, 14 unresolved discussions (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50)* status: all files reviewed, 13 unresolved discussions (waiting on @AlexandreAmice)

___
*[`bindings/pydrake/multibody/rational_forward_kinematics_py.cc` line 156 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pmvC78EgKcz-LrBAz:-N7vAVe87Vkq_1wI23w0:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L156)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Missing the "kCapsule"
</blockquote></details>

Done.
___
*[`bindings/pydrake/multibody/rational_forward_kinematics_py.cc` line 320 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pnK2S8DCjpfm6YznH:-N7vHnnT6CC5DWHz2_U3:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L320)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

As noted later, consider renaming this to `map_geometries_to_separating_planes` or something similar
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/collision_geometry.h` line 22 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pYWhA9lSeoAh4sKzQ:-N7vBCeh3r9pUKcM0NDN:b-h5g1tk) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.h#L22)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Why no copy no move and no assign?
</blockquote></details>

Done. Good call
___
*[`multibody/rational_forward_kinematics/collision_geometry.h` line 49 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pYxkt6zvTro-Ok3Hx:-N7vBRTh-uKMNh4Y5bOz:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.h#L49)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add some documentation on this method? It makes a lot of sense for polytopes but I'm not sure I understand the expected behavior for other convex shapes. 
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/collision_geometry.cc` line 35 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pZFLA8WDunmuyXBG7:-N7vCqx3DCHpuVXlVVia:bk0qfw2) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.cc#L35)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I am not sure I understand this implementation. Some extra comments may help as would documentation in the header file
</blockquote></details>

Done. I add the documentation.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 42 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pZUr03klj5q3fS9HF:-N7vDCbc8Bix0xXI1HW9:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L42)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

add `\delta \geq 0` to documentation
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 205 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7p_26_0rTR949sOuju:-N7vDcbs35SFNmxavcuK:b-gphy8s) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L205)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

We  may want to document why we call this a_A. I.e. explain the purpose of the expressed in link in the documentation.
</blockquote></details>

Done. I add the documentation in the data field.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 278 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pXS6o2BaV4rnj1PYy:-N7vDzTnCEkKQELJAcgO:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L278)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

I think this would make more sense to call map_geometries_to_separating_planes
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 289 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pdYip6Vg73nwj49la:-N7vEPBx-kCOlEQUwKHI:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.h#L289)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Can we change this to `GenerateRationalsForLinkOnOneSideOfPlane`. It would be more grammatically correct?
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 263 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pbVg_0gl8S8mfTwuC:-N7vEb1C8wtBKQ-65giH:b-r6vusg) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L263)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

perhaps we don't specify "for_polytope" here and just leave in the documentation that plane_order_ only works for polytopes. Regardless I think this name as written may be somewhat confusing.
</blockquote></details>

This `plane_order_for_polytope_` will soon be replaced in the next PR. Currently in this PR we only support affine order separating plane for polytopes, not for spheres/capsules/cylinders. In the next PR we will support affine order for all geometries. 
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 1786 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pfTV6-yg6dFUYrROq:-N7vGMxBBPoJzUUlssD0:b-o7d5gy) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L1786)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This lambda is getting to be quite large. Should we move it to its own stand-alone private method? Or at least break extract the is_success clause into its own lambda or method.
</blockquote></details>

I leave a TODO here. Doing the refactorization in this PR might cause conflict with the next PR. I will refactor this function after the next PR (which supports affine-order separating planes for sphere/cylinder/capsule geometries)
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 1978 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pj052AjcRv2IgMy-L:-N7vHLU5-U1AXnEdU7bp:bhxwii4) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L1978)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

What is p_AQ
</blockquote></details>

It's our notation for position of point Q measured and expressed in frame A. This is a standard notation inside Drake.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2011 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pj6JU7LQ7CL6y8Qo9:-N7vHmcS5xE6OiA7Z0Sm:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/cspace_free_region.cc#L2011)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Maybe add documentation explaining that we compute the rational for every polytope vertex to be consistent with the other two cases.
</blockquote></details>

Done.

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

**Review by AlexandreAmice — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50#-:-N80YBOHAn84qesFyXmH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`multibody/rational_forward_kinematics/collision_geometry.cc` line 35 at r1](https://reviewable.io/reviews/alexandreamice/drake/50#-N7pZFLA8WDunmuyXBG7:-N80Z5fK77XRmm9CbEJj:b-ub2d1s) ([raw file](https://github.com/alexandreamice/drake/blob/822b578d7efa2c705c6786d151f1c2bd7b071961/multibody/rational_forward_kinematics/collision_geometry.cc#L35)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I add the documentation.
</blockquote></details>

If you are satisfied, could you acknowledge this comment? We can then merge this PR.

**Review by AlexandreAmice — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/50)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
