### PR TITLE
add some hpolyhedron methods

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41)

### CODE REVIEW

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Have you thought about sending this PR to drake master?

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41#-:-N-i8xXP264-Geo-LQsC:b-9qlyj)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.h, line 59 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-i6Xip-DzYN9hZigO1:-N-i6Xip-DzYN9hZigO2:b2v26oi) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/geometry/optimization/hpolyhedron.h#L59)):*
> ```objc
>    * redundant when added to this.
>    */
>   bool ContainedInOtherHPolyhedron(const HPolyhedron& other) const;
> ```

BTW, you could rename this function as `Contained`. The input type `HPolyhedron` already suggests "InOtherHPolyhedron".
___
*[geometry/optimization/hpolyhedron.h, line 66 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-i7KWlBVb5VUNKzQin:-N-i7KWlBVb5VUNKzQio:b1u3do) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/geometry/optimization/hpolyhedron.h#L66)):*
> ```objc
>    * implied by the inequalities from this HPolyhedron.
>    */
>   HPolyhedron IrredundantIntersection(const HPolyhedron& other) const;
> ```

I am not sure if the intersection is irredundant. It certainly reduces the number of inequalities than just concantenating the A/b matrices of this and other h-polyhedrons, but I am not convinced that the returned h-polyhedron has the minimal representation.
The implementation you have seems to depend on the specific order. If I have two polyhedrons C and D, while C is a subset of D. Then it seems to me that calling C.IrredundantIntersection(D) would just return me C, but calling D.IrredundantIntersection(C) would return me an h-polyhedron that concantentate the matrices of C and D.

Maybe just change the name to "Intersection"?

**Review by AlexandreAmice — COMMENTED** [review]
I could send it over as a separate PR, it is useful in some of the C_Iris stuff so would appreciate it being merged sooner than through master

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41#-:-N-ijIde2ndAwaFUSp1y:byckibk)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[geometry/optimization/hpolyhedron.h, line 59 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-i6Xip-DzYN9hZigO1:-N-iiVm69EaD8HBqHgfX:boegsj6) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/geometry/optimization/hpolyhedron.h#L59)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, you could rename this function as `Contained`. The input type `HPolyhedron` already suggests "InOtherHPolyhedron".
</blockquote></details>

Changed to "ContainedIn"
___
*[geometry/optimization/hpolyhedron.h, line 66 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-i7KWlBVb5VUNKzQin:-N-ij6ZD5YJShT-IjBRu:b-b5e4bm) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/geometry/optimization/hpolyhedron.h#L66)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not sure if the intersection is irredundant. It certainly reduces the number of inequalities than just concantenating the A/b matrices of this and other h-polyhedrons, but I am not convinced that the returned h-polyhedron has the minimal representation.
The implementation you have seems to depend on the specific order. If I have two polyhedrons C and D, while C is a subset of D. Then it seems to me that calling C.IrredundantIntersection(D) would just return me C, but calling D.IrredundantIntersection(C) would return me an h-polyhedron that concantentate the matrices of C and D.

Maybe just change the name to "Intersection"?


</blockquote></details>

That is indeed the expected behavior. It is hard to get a minimal representation and so I did not want to bother with that complexity.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 16 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-imshV2IzZufySMdd_:-N-imshV2IzZufySMdda:b-ort02e) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L16)):*
> ```cpp
> #include "drake/multibody/rational_forward_kinematics/rational_forward_kinematics.h"
> #include "drake/multibody/rational_forward_kinematics/rational_forward_kinematics_internal.h"
> #include "drake/multibody/rational_forward_kinematics/centrally_symmetric_hpolytope.h"
> ```

I don't see this file in rational_forward_kinematics folder?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 16 at r1](https://reviewable.io/reviews/alexandreamice/drake/41#-N-imshV2IzZufySMdd_:-N-ipht58tdXgNPeSvNv:bwzmtax) ([raw file](https://github.com/alexandreamice/drake/blob/a7cc863c26b671bdcd34a063ccf16cb8df353fc3/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L16)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't see this file in rational_forward_kinematics folder?
</blockquote></details>

Removed. Sorry it was done due to a bad copy paste

**Review by hongkai-dai — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/41#-:-N-jWO_75_nJyhzQU1om:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
