### PR TITLE
Overhaul visualization

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Rewrite visualization and update 2d pinball example

- - -
This change is [Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/66)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai this is a fairly large change, but it greatly simplifies the mess of the backend python code I was using for visualization

> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/66#-:-NMjvmRl45yrQlH7VnV4:b-ues5m9)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/66)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`C_Iris_Examples/pinball_iiwas_2d.ipynb` line 2 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/66#-NMkGyAu0-dBu0g_LCs_:-NMkGyAu0-dBu0g_LCsa:bv44rjb) ([raw file](https://github.com/AlexandreAmice/drake/blob/ef434b34ed34b2bf66d5acfddd5d3bac72978c20/C_Iris_Examples/pinball_iiwas_2d.ipynb#L2)):*
> ```
> {
>  "cells": [
> ```

Could you clear the cell output?

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/66#-:-NMkYeBI6TGzddICy3yJ:bg7igkv)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/66)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
