### PR TITLE
C iris deepnote

### PR DESCRIPTION
**Pull request by AlexandreAmice**
update to master and finalize notebook examples

- - -
This change is [Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/69)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for review though this is quite a change

> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/69#-:-NOzdlAz969Az8dGfppZ:b-yblpef)* status: 0 of 700 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 4 of 700 files at r1.
> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/69)* status: 4 of 700 files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[`C_Iris_Examples/dual_ur.ipynb` line 270 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NOzqYUf4H_y5Ds30Y9X:-NOzqYUf4H_y5Ds30Y9Y:beu48kh) ([raw file](https://github.com/AlexandreAmice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/dual_ur.ipynb#L270)):*
> ```
>    "source": [
>     "save_posture_file = \"dual_ur_closest.npz\"\n",
>     "ur3e_demo.sample_closest_posture(ur, rational_forward_kin, q_star,\n",
> ```

I wonder if we should fix the random seed for the sampling here. I sometimes sample some postures that are farther apart.
___
*[`C_Iris_Examples/single_ur.ipynb` line 11 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NOzqt3ACTF9ZQIcP99e:-NOzqt3ACTF9ZQIcP99f:b-yjhwrh) ([raw file](https://github.com/AlexandreAmice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/single_ur.ipynb#L11)):*
> ```
>    },
>    "source": [
>     "# 5DOF Robot with a shelf\n",
> ```

Just curious why we use a 5DOF UR instead of the 6DOF version. I think both version give comparable SOS problems (since the longest kinematics chain from the plane to the geometry is 3 in both cases).

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/69)* status: 4 of 700 files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`C_Iris_Examples/dual_ur.ipynb` line 270 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NOzqYUf4H_y5Ds30Y9X:-NP-CSum2LiJ8sqVHu4h:brrt4xq) ([raw file](https://github.com/AlexandreAmice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/dual_ur.ipynb#L270)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I wonder if we should fix the random seed for the sampling here. I sometimes sample some postures that are farther apart.
</blockquote></details>

Done. I also increased the range of random samples of `s_samples`
___
*[`C_Iris_Examples/single_ur.ipynb` line 11 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NOzqt3ACTF9ZQIcP99e:-NP-DYwUAjNVTj5az1IK:b-6y3ww7) ([raw file](https://github.com/AlexandreAmice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/single_ur.ipynb#L11)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Just curious why we use a 5DOF UR instead of the 6DOF version. I think both version give comparable SOS problems (since the longest kinematics chain from the plane to the geometry is 3 in both cases).
</blockquote></details>

There is no technical reason. I just changed it to 6DOF. 

The practical reason is I never got around to debugging this [typo](https://github.com/hongkai-dai/drake/blob/72293e9ed7b01b7fca9e52113da88ae7b0b5395a/geometry/optimization/dev/test/ur3e_demo.py#L48) in th eoriginal `ur_demo.py` file.

Should be fixed now.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 5 of 700 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/AlexandreAmice/drake/69#-:-NP-GPEp4w2NTeeC8Yr9:bg7igkv)* status: 10 of 700 files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice)

___
*[`C_Iris_Examples/single_ur.ipynb` line 11 at r1](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NOzqt3ACTF9ZQIcP99e:-NP-FqkD-qD81dE60GsE:bichbis) ([raw file](https://github.com/AlexandreAmice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/single_ur.ipynb#L11)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

There is no technical reason. I just changed it to 6DOF. 

The practical reason is I never got around to debugging this [typo](https://github.com/hongkai-dai/drake/blob/72293e9ed7b01b7fca9e52113da88ae7b0b5395a/geometry/optimization/dev/test/ur3e_demo.py#L48) in th eoriginal `ur_demo.py` file.

Should be fixed now.
</blockquote></details>

Change this line to say "6DOF robot with a shelf\n"?
___
*[`C_Iris_Examples/single_ur.ipynb` line 12 at r2](https://reviewable.io/reviews/AlexandreAmice/drake/69#-NP-FveCALWKttmwkiz8:-NP-FveCALWKttmwkiz9:byewz6s) ([raw file](https://github.com/AlexandreAmice/drake/blob/2f5f962435232cca142779054ade41e05ee7b86a/C_Iris_Examples/single_ur.ipynb#L12)):*
> ```
>    "source": [
>     "# 5DOF Robot with a shelf\n",
>     "In this notebook, we deploy our algorithm on a 5DOF robot interacting with a shelf. We demonstrate that combining Algorithm 2 in Appendix F of \"Certified Polyhedral Decompositions of Collision-Free Configuration Space\" with the certification algorithm given in Algorithm 1 can yield certified configuration-space regions that can reach a large amount of task space.\n",
> ```

Change 5DOF to 6DOF?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/69)* status: 9 of 700 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[`C_Iris_Examples/single_ur.ipynb` line 11 at r1](https://reviewable.io/reviews/alexandreamice/drake/69#-NOzqt3ACTF9ZQIcP99e:-NP2jvyB4goanUaZmu4f:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/9a9f5d931540f97d68be0e9e240299dde46214d7/C_Iris_Examples/single_ur.ipynb#L11)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Change this line to say "6DOF robot with a shelf\n"?
</blockquote></details>

Done.
___
*[`C_Iris_Examples/single_ur.ipynb` line 12 at r2](https://reviewable.io/reviews/alexandreamice/drake/69#-NP-FveCALWKttmwkiz8:-NP2jwDzB128X5J1qvZl:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/2f5f962435232cca142779054ade41e05ee7b86a/C_Iris_Examples/single_ur.ipynb#L12)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Change 5DOF to 6DOF?
</blockquote></details>

Done.

**Pull request merged**
