### PR TITLE
Cover polytope with boxes.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13#-:-Mte60Gg3svWtYP_Gh7b:b-kengf8)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

___
*[geometry/optimization/polytope_cover.cc, line 65 at r1](https://reviewable.io/reviews/alexandreamice/drake/13#-MteEDka0b_xnU53nbYB:-MteEDka0b_xnU53nbYC:b-b13ijv) ([raw file](https://github.com/alexandreamice/drake/blob/3fa97178f1ba495236aa78e96fc687b0890b8c3a/geometry/optimization/polytope_cover.cc#L65)):*
> ```cpp
> // Add the constraint that box_lo <= x <= box_up doesn't overlap with the other
> // obstacle box. The box box_lo <= x <= box_up has to lie within outer_box.
> VectorX<symbolic::Variable> AddBoxNoOverlapping(
> ```

Spelling: AddBoxNotOverlapping



_Code quote:_
```cpp
AddBoxNoOverlapping
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[geometry/optimization/polytope_cover.cc, line 65 at r1](https://reviewable.io/reviews/alexandreamice/drake/13#-MteEDka0b_xnU53nbYB:-MteQ9kY16Kd1qKjcVJj:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/3fa97178f1ba495236aa78e96fc687b0890b8c3a/geometry/optimization/polytope_cover.cc#L65)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Spelling: AddBoxNotOverlapping
</blockquote></details>

Done.

**Review by AlexandreAmice — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by AlexandreAmice — APPROVED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/13#-:-Mtf5LWM6XJGKjNhEnOT:bmxilld)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
