### PR TITLE
Write cspace free region to file bindings

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This is still failing a test, which I am digging into. I am creating this PR for some review on the design philosophy of the functions themselves and the binding.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
@hongkai-dai for review. Thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48#-:-N3g0VbG8M1mb6v36RDm:b5jmuos)* status: 0 of 7 files reviewed, all discussions resolved

**Review by AlexandreAmice — COMMENTED** [review]
> .
+@hongkai-dai  

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48#-:-N3j7BDA5Fls2b0E4Gp_:b-7l0f6u)* status: 0 of 7 files reviewed, all discussions resolved

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai 

Sorry took me a few times to type the right syntax!  

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48#-:-N3j7G2C64CBsyYCcvI8:b-qd5ejl)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
PTAL.

> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48#-:-N3jqJcQ2irNhCCZQYgr:b-83330m)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/convex_geometry.h` line 100 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3joOLmD2wbhCYbGtb6:-N3joOLmD2wbhCYbGtb7:b-9lq6op) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/convex_geometry.h#L100)):*
> ```objc
>   const Eigen::Vector3d& p_BC() const override { return p_BC_; }
> ```

No change here? Could you revert change on this file?
___
*[`multibody/rational_forward_kinematics/convex_geometry.cc` line 155 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3joTuM7m50v3pIknMG:-N3joTuM7m50v3pIknMH:b7yeiyx) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/convex_geometry.cc#L155)):*
> ```cpp
>   prog->AddLorentzConeConstraint(lorentz_expr);
> }
> ```

Could you revert change on this file?
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 861 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jpiURBqM56Q1BTYud:-N3jpiURBqM56Q1BTYue:b-e2mkgx) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.h#L861)):*
> ```objc
>     const geometry::SceneGraphInspector<double>& inspector, Eigen::MatrixXd* C,
>     Eigen::VectorXd* d,
>     std::unordered_map<SortedPair<std::pair<BodyIndex, geometry::GeometryId>>,
> ```

Why adding `BodyIndex` to `std::pair<BodyIndex, geometry::GeometryId>`? I would think the pair of geometry Ids uniquely determines the separating pair, and don't need additional information on the body.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2435 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jomsn9Qka9JeX9pOu:-N3jomsn9Qka9JeX9pOv:bfcmq3) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2435)):*
> ```cpp
>       ss = std::istringstream(line);
>       ss >> word;
>       const SeparatingPlaneOrder order = word == "kAffine"
> ```

This line assumes we have only two orders, either affine or constant. While this is true for now, it might not work when we extend to other orders in the future, so I would suggest to compare `word` against `kAffine` and `kConstant`, and throw an error if there is not match.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2518 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jpEau1X2DLoXraKcG:-N3jpEau1X2DLoXraKcH:bii8wn7) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2518)):*
> ```cpp
>   for (const std::pair<
>            SortedPair<std::pair<BodyIndex, geometry::GeometryId>>,
>            std::tuple<BodyIndex, Eigen::VectorXd, SeparatingPlaneOrder>>& elt :
> ```

`elt` is not a very meaningful name, consider to change it?

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/convex_geometry.h` line 100 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3joOLmD2wbhCYbGtb6:-N3pFZcC6pCJTq-r2DAh:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/convex_geometry.h#L100)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

No change here? Could you revert change on this file?
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/convex_geometry.cc` line 155 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3joTuM7m50v3pIknMG:-N3pFZzP6-K4NqTDjlRn:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/convex_geometry.cc#L155)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you revert change on this file?
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 861 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jpiURBqM56Q1BTYud:-N3pFxTMCeg8GvaF17cQ:b-pan8yq) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.h#L861)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why adding `BodyIndex` to `std::pair<BodyIndex, geometry::GeometryId>`? I would think the pair of geometry Ids uniquely determines the separating pair, and don't need additional information on the body.
</blockquote></details>

When I write the overloaded function that actually fully reconstructs a `CspaceFreeRegionSolution` object, I call the `CalcPlane` method which requires the `BodyIndex`. My understanding is the `GeometryId` is the id of the object within `SceneGraph` while `BodyIndex` is the id within `MultibodyPlant` and so it would make sense to store the whole pair to me.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2435 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jomsn9Qka9JeX9pOu:-N3pJsiF9A2naaYE2HAl:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2435)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This line assumes we have only two orders, either affine or constant. While this is true for now, it might not work when we extend to other orders in the future, so I would suggest to compare `word` against `kAffine` and `kConstant`, and throw an error if there is not match.
</blockquote></details>

Done.
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2518 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jpEau1X2DLoXraKcG:-N3pKarA2CUYCnbT87Xr:b2umdln) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2518)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`elt` is not a very meaningful name, consider to change it?
</blockquote></details>

Change to "plane_pair_ids_to_plane_info". The dictionary itself contains quite complex items so it is not clear to me if there is a succinct name for this.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/48)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 861 at r1](https://reviewable.io/reviews/alexandreamice/drake/48#-N3jpiURBqM56Q1BTYud:-N3thEWD02Yw6maGElLD:bgbsnpb) ([raw file](https://github.com/alexandreamice/drake/blob/a2cb460c391ce52fdcfbac32e8496c5214885c5b/multibody/rational_forward_kinematics/cspace_free_region.h#L861)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

When I write the overloaded function that actually fully reconstructs a `CspaceFreeRegionSolution` object, I call the `CalcPlane` method which requires the `BodyIndex`. My understanding is the `GeometryId` is the id of the object within `SceneGraph` while `BodyIndex` is the id within `MultibodyPlant` and so it would make sense to store the whole pair to me.
</blockquote></details>

I think you could get the BodyIndex from the GeometryId
```cc
const SceneGraphInspector<double>& inspector = scene_graph.model_inspector();
const FrameId frame_id = inspector.GetFrameId(geometry_id);
const BodyIndex body_index = plant.GetBodyFromeFrameId(frame_id)->index();
```

I do think it is better to make this `unordered_map` simpler. Currently the key of this map is `SortedPair<std::pair<BodyIndex, GeometryId>>` which is quite complicated.

**Pull request closed without merging**
