### PR TITLE
Add dual IIWA demo.

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
There are several files in here modifying CspaceFreeRegion and I am not sure why? If your intention is to only add the dual IIWA demo could you please split this into two PR's as well as help me understand what is changing and why in the CspaceFreeRegion.

> Reviewed 4 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N6PB2P32tMQ3B5Qc0Pk:bc71vbd)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by hongkai-dai — COMMENTED** [review]
Done. Sorry for the delay. It has been too long since last time I touched this code, and I forgot which part of the change is needed. I end up only including the changes in this  PR that makes compilation to succeed.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N7MTfuLEf94tnVbBqrk:b62log)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
This modifies the `WriteCspacePolytopeToFile` and `ReadCspacePolytopeFromFile`. Did you rerun the tests to validate? When I try to run `bazel test multibody/...` I get compilation errors

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N7R8BzE3ZUeS-ZoC5Ff:bhgih6u)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
What is the error message when you run the test? I also tested the code and it works fine.

BTW, you will need to pass the flag `--config mosek` when running the bazel test. So the command is
```
bazel test -config mosek //multibody/rational_forward_kinematics/...
```

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N7SBTF10eNaB6raMBLp:bigbbs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
Apologies you are correct I had just messed up some git stuff. However, I do get a linting error in dual_iiwa_demo:

```multibody/rational_forward_kinematics/test/dual_iiwa_demo.cc:108:  Constructors callable with one argument should be marked explicit.  [runtime/explicit] [5]```

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N80YnMw34sbA3cjVIv3:busr6eg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
Done. I fixed the linting error in dual_iiwa_demo.cc

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N80fkYY-GIeLJryNHTi:b-ewfeda)* status: 1 of 8 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
Sorry looks like there is still some weird spacing stuff left in `cspace_free_region.h`, `cspace_free_region_test.cc`, and `iiwa_shelf_demo`

> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N845kpCCAI_EclOXaBM:bfjkb0i)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_region.h` line 197 at r3](https://reviewable.io/reviews/alexandreamice/drake/49#-N8495wA5LVzTPKV9-uC:-N8495wA5LVzTPKV9-uD:b-nfbtvi) ([raw file](https://github.com/alexandreamice/drake/blob/d66dec6228c1975f23a777ebb3e2130452efab9b/multibody/rational_forward_kinematics/cspace_free_region.h#L197)):*
> ```objc
>        multibody::BodyIndex m_expressed_body_index,
>        const CollisionGeometry* m_other_side_link_geometry,
>        Vector3<symbolic::Expression> m_a_A, symbolic::Expression m_b,
> ```

This file seems to have some weird indentation that happened? I have the error ```multibody/rational_forward_kinematics/cspace_free_region.h:218:  Weird number of spaces at line-start.  Are you using a 2-space indent?```
___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2591 at r3](https://reviewable.io/reviews/alexandreamice/drake/49#-N8464S95oCor-irRNro:-N8464S95oCor-irRNrp:b-cwqk02) ([raw file](https://github.com/alexandreamice/drake/blob/d66dec6228c1975f23a777ebb3e2130452efab9b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2591)):*
> ```cpp
>           << plant.get_body(plane.negative_side_geometry->body_index()).name()
>           << "\n";
>       myfile << inspector.GetName(plane.negative_side_geometry->id()) << "\n";
> ```

Lost the // geometry name comment

**Review by hongkai-dai — COMMENTED** [review]
These linting errors are not introduced in this PR, but previous PRs. (Actually I never ran linting test on this branch before). To keep each commit simple (that it only does one thing in each commit), I think it is better to merge the PR in this current status, and then file a separate PR to fix the linting errors. What do you think?

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N84il34DIH3RmVx2Mnv:bkl09je)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

**Review by AlexandreAmice — COMMENTED** [review]
That is fine. I will merge master soon and can fix those errors. The only thing remaining is the one deleted comment on the geometry name.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N84uF3x0ge01FV7Sa0C:bps90b7)* status: all files reviewed, 1 unresolved discussion (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`multibody/rational_forward_kinematics/cspace_free_region.cc` line 2591 at r3](https://reviewable.io/reviews/alexandreamice/drake/49#-N8464S95oCor-irRNro:-N84vSIvAgMtgFN5hZAy:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/d66dec6228c1975f23a777ebb3e2130452efab9b/multibody/rational_forward_kinematics/cspace_free_region.cc#L2591)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Lost the // geometry name comment
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
Done. I added the comment on the geometry name

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N84vfLa3xi1AG0cxFFL:b98xbhl)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

**Review by AlexandreAmice — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by AlexandreAmice — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/49#-:-N84wPp79jzRq3ba1Kss:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
