### PR TITLE
add an example of IIWA + shelf

### PR DESCRIPTION
**Pull request by hongkai-dai**
The bilinear alternation should increase the inscribed ellipsoid volume.
But sometimes it decreases.

I suspect this is a numerical problem of Mosek, the evidence is that if I fix the inscribed ellipsoid to the value found in the previous iteration, then the "lagrangian program" is still feasible, but if I allow the inscribed ellipsoid to change, it finds an ellipsoid with smaller volume, although the objective is to maximize the ellipsoid volume.

I am going to try to change the objective from log(det(P)) to power(det(P), 1/m). The former objective uses an exponential cone, while the latter objective replaces the exponential cone with second order cones. Hence I expect the latter to have better numerical performance. I will send a separate PR to do this.

BTW, here is the test scenario, I use a 7 DOF iiwa with boxed schunk gripper and the shelf. This is the seed posture
iiwa_shelf

One thing to note is that the optimization takes a lot longer than I expected. Now the Lagrangian step takes ~2 minutes, and the polytope step takes 3s. I am checking why it takes so long.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11#-:-MtGpt-u-Tgork7C0jZB:b-kengf8)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1055 at r1](https://reviewable.io/reviews/alexandreamice/drake/11#-MteCA1-DIgceS7hgQSl:-MteCA1-DIgceS7hgQSm:bjlx1ai) ([raw file](https://github.com/alexandreamice/drake/blob/62d0c7759b37e7a22e106f62cb4020a099bbe6ae/multibody/rational_forward_kinematics/cspace_free_region.cc#L1055)):*
> ```cpp
>         nullptr);
>     // Now add the constraint that C*t<=d , t_lower <= t <= t_upper is not
>     // empty. We find t_nominal satisfying these constraints.
> ```

This implicitly forces that the IrisRegion contain the seed point. This is an option when running IrisInRationalSpace, so this may cause conflicts if the user isn't aware that this is required
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 989 at r2](https://reviewable.io/reviews/alexandreamice/drake/11#-MteD6jU8H8Lharf8Ww7:-MteD6jU8H8Lharf8Ww8:bnpk7ci) ([raw file](https://github.com/alexandreamice/drake/blob/3f4073dec04e81c9ba8f812cbd58b53a76c6afd7/multibody/rational_forward_kinematics/cspace_free_region.cc#L989)):*
> ```cpp
>     // Maximize the geometric mean of (margin + epsilon), where epsilon is a
>     // small positive number to make sure this geometric mean is always
>     // positive, even when some of margin is 0.
> ```

Unclear what you are saying when you maximize (margin + epsilon). Does this mean that your cost is geom_mean(margin) + sum(epsilon)? If so, log-det is no longer monotonically related the cost here.



_Code quote:_
```cpp
AddMaximizeGeometricMeanCost
```

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1055 at r1](https://reviewable.io/reviews/alexandreamice/drake/11#-MteCA1-DIgceS7hgQSl:-MteGAWp82a6y7EuHH-X:bn5x026) ([raw file](https://github.com/alexandreamice/drake/blob/62d0c7759b37e7a22e106f62cb4020a099bbe6ae/multibody/rational_forward_kinematics/cspace_free_region.cc#L1055)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This implicitly forces that the IrisRegion contain the seed point. This is an option when running IrisInRationalSpace, so this may cause conflicts if the user isn't aware that this is required
</blockquote></details>

This doesn't really say the polytope C*t<=d contains the seed point, but just C*t<=d, t_lower<=t <= t_upper is non-empty. Otherwise when we shrink the polytope, it could shrink to an empty set.

This is an interesting point, maybe when we shrink the polytope, we should first find epsilon_min such that C*t <= d + epsilon_min is almost infeasible, this give us a lower bound of valid epsilon_min. I add a TODO here to fix it in the next PR.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 989 at r2](https://reviewable.io/reviews/alexandreamice/drake/11#-MteD6jU8H8Lharf8Ww7:-MteFYHz3tNnKA7FBZgA:bmvz1h7) ([raw file](https://github.com/alexandreamice/drake/blob/3f4073dec04e81c9ba8f812cbd58b53a76c6afd7/multibody/rational_forward_kinematics/cspace_free_region.cc#L989)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Unclear what you are saying when you maximize (margin + epsilon). Does this mean that your cost is geom_mean(margin) + sum(epsilon)? If so, log-det is no longer monotonically related the cost here.
</blockquote></details>

Done. I modified the documentation to make it more clear. 

To encourage increasing every entry of margin, I would like to maximize product(margin(i)), but if some face cannot be moved at all (for example the polytope C*t<=d already touches the C-space obstacle on some face), then the margin for that face would be zero, making the whole product also zero, no matter what value the other margin take. So I add a small epsilon to make sure the product is strictly positive.

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1055 at r1](https://reviewable.io/reviews/alexandreamice/drake/11#-MteCA1-DIgceS7hgQSl:-MtkKSoG4EnIHPMByMpf:b5rnr5f) ([raw file](https://github.com/alexandreamice/drake/blob/62d0c7759b37e7a22e106f62cb4020a099bbe6ae/multibody/rational_forward_kinematics/cspace_free_region.cc#L1055)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This doesn't really say the polytope C*t<=d contains the seed point, but just C*t<=d, t_lower<=t <= t_upper is non-empty. Otherwise when we shrink the polytope, it could shrink to an empty set.

This is an interesting point, maybe when we shrink the polytope, we should first find epsilon_min such that C*t <= d + epsilon_min is almost infeasible, this give us a lower bound of valid epsilon_min. I add a TODO here to fix it in the next PR.
</blockquote></details>

This makes more sense now. I have this program already implemented in python the file certified_iris_generator.py under the function _initialize_max_eps_via_max_shrinkage(). It find the maximum (in the L1 norm) epsilon such that Ct <= d- eps contains the seed point.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1068 at r3](https://reviewable.io/reviews/alexandreamice/drake/11#-MtkKlIj1lYcZY1lqvSH:-MtkKlIj1lYcZY1lqvSI:bdf2qi0) ([raw file](https://github.com/alexandreamice/drake/blob/02f6f8a79562bdd234b6c63eec8d0d96149b885a/multibody/rational_forward_kinematics/cspace_free_region.cc#L1068)):*
> ```cpp
>     // Now add the constraint that C*t<=d , t_lower <= t <= t_upper is not
>     // empty. We find t_nominal satisfying these constraints.
>     // TODO(hongkai.dai): find the lower bound of epsilon throug such that
> ```

Extra word: throug

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11)* status: all files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1055 at r1](https://reviewable.io/reviews/alexandreamice/drake/11#-MteCA1-DIgceS7hgQSl:-MtkMcWh6V5YGZGzwn-n:b1bx5hk) ([raw file](https://github.com/alexandreamice/drake/blob/62d0c7759b37e7a22e106f62cb4020a099bbe6ae/multibody/rational_forward_kinematics/cspace_free_region.cc#L1055)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

This makes more sense now. I have this program already implemented in python the file certified_iris_generator.py under the function _initialize_max_eps_via_max_shrinkage(). It find the maximum (in the L1 norm) epsilon such that Ct <= d- eps contains the seed point.
</blockquote></details>

Cool, I also implemented the function in C++ in a dev branch. If we merge this PR, I can send that dev branch as a follow-up PR. My implementation doesn't require it to contain the seed point, but just C*t <= d-eps is non-empty.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1068 at r3](https://reviewable.io/reviews/alexandreamice/drake/11#-MtkKlIj1lYcZY1lqvSH:-MtkN40j-jxt9ib4sGvk:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/02f6f8a79562bdd234b6c63eec8d0d96149b885a/multibody/rational_forward_kinematics/cspace_free_region.cc#L1068)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Extra word: throug
</blockquote></details>

Done.

**Review by hongkai-dai — COMMENTED** [review]
@alexandreamice I addressed your comments, PTAL.

If you are satisfied with the code, you could clock "Acknowledge" button for each of the comment. Once all comments are resolved we can then merge this PR.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11#-:-MtpF9NY8-JnZhS5V-OT:bb0ohg8)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @AlexandreAmice)

**Review by AlexandreAmice — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/11#-:-MtpGMSbBUQraH6eoPP6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
