### PR TITLE
Use k'th root of the ellipsoid volume as the cost.

### PR DESCRIPTION
**Pull request by hongkai-dai**
Avoid using exponential cone constraints.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/25)

### CODE REVIEW

**Review by AlexandreAmice — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/25)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 440 at r1](https://reviewable.io/reviews/alexandreamice/drake/25#-MusM3Y3ECspDy3ZC_r-:-MusM3Y3ECspDy3ZC_r0:b8o2tcl) ([raw file](https://github.com/alexandreamice/drake/blob/c1c57059d99c73fa26b3b516a8653f9108737766/multibody/rational_forward_kinematics/cspace_free_region.h#L440)):*
> ```objc
>     // Whether to compute and print the volume of the C-space polytope.
>     bool compute_polytope_volume{false};
>     std::optional<double> redundant_tighten{0};
> ```

Needs documentation on what this means
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1179 at r1](https://reviewable.io/reviews/alexandreamice/drake/25#-MusN-9o-bM9EICumX3P:-MusN-9o-bM9EICumX3Q:bkob0q5) ([raw file](https://github.com/alexandreamice/drake/blob/c1c57059d99c73fa26b3b516a8653f9108737766/multibody/rational_forward_kinematics/cspace_free_region.cc#L1179)):*
> ```cpp
> }
> 
> void CspaceFreeRegion::CspacePolytopeBinarySearch(
> ```

Just as a comment. Shouldn't we call this bisection search? I am not sure when we both started calling it binary search

**Review by AlexandreAmice — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/25#-:-MusNTi55LqY6QwckdFh:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @hongkai-dai)

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/25)* status: all files reviewed, 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 440 at r1](https://reviewable.io/reviews/alexandreamice/drake/25#-MusM3Y3ECspDy3ZC_r-:-MuvMSIA83O8pJztT1yM:b9qk051) ([raw file](https://github.com/alexandreamice/drake/blob/c1c57059d99c73fa26b3b516a8653f9108737766/multibody/rational_forward_kinematics/cspace_free_region.h#L440)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Needs documentation on what this means
</blockquote></details>

Done. I removed this. As discussed yesterday, the real reason why search_d fails is the problem being unbounded (solved through PR #26 ), not whether removing redundant constraints or not.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1179 at r1](https://reviewable.io/reviews/alexandreamice/drake/25#-MusN-9o-bM9EICumX3P:-MuvNcHS2M0pTDBwv_Dg:b9soyak) ([raw file](https://github.com/alexandreamice/drake/blob/c1c57059d99c73fa26b3b516a8653f9108737766/multibody/rational_forward_kinematics/cspace_free_region.cc#L1179)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Just as a comment. Shouldn't we call this bisection search? I am not sure when we both started calling it binary search
</blockquote></details>

I thought they mean the same thing, as said in this wiki https://en.wikipedia.org/wiki/Bisection_method
```
The method is also called the interval halving method,[2] the binary search method,[3] or the dichotomy method
```

If you prefer Bisection (which is a shorter name than BinarySearch, and I like this shorter name), I can file a separate PR to change it (I prefer to do it in a separate PR so that each PR does one thing). BTW, I think it is better to use "bisection" instead of "bisection search", as used in this wiki page.

**Review by AlexandreAmice — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
