### PR TITLE
Sos iris experimental

### PR DESCRIPTION
**Pull request by AlexandreAmice**
Sorry about the big PR. I did not realize that I wasn't PRing correctly

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai  for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17#-:-MtuG-ey82NlkA04VbgL:b5p6ue9)* status: 0 of 29 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
I am not sure why it includes many of the changes I already reviewed last time. I will ignore these changes and only review the new changes.

> Reviewed 24 of 29 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17#-:-Mu1brQU6J93hMBZI4rV:be4eoex)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @AlexandreAmice)

___
*[geometry/optimization/hpolyhedron.cc, line 272 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1cONI9HZfdeMUe2Ov:-Mu1cONI9HZfdeMUe2Ow:bixcqb7) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/geometry/optimization/hpolyhedron.cc#L272)):*
> ```cpp
>   const int num_vars = A_.cols();
> 
>   int num_kept = num_inequalities;
> ```

BTW, as mentioned in the previous PR, `num_kept` is redundant, you could use `kept_indices.size()`. 
___
*[geometry/optimization/test/hpolyhedron_test.cc, line 488 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1dNYN5MMoNEk3aXFz:-Mu1dNYN5MMoNEk3aXG-:b-e9anmi) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/geometry/optimization/test/hpolyhedron_test.cc#L488)):*
> ```cpp
>           -0.        ,-1.        , -0.        ,
>           -0.        ,-0.        , -1.        ,
>            0.14569377, 0.97734161, -0.15354705,
> ```

BTW, as mentioned in the previous PR's comment, these numbers are magic. Is it OK if you could use a simpler test? As far as I can see, as long as the two polyhedron intersect then this test should pass, so maybe you can use a simpler polyhedron, like a box, a tetrahedron, or octahedron?
___
*[geometry/optimization/test/iris_test.cc, line 385 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1dyNT25Hc8x2wEGmw:-Mu1dyNT25Hc8x2wEGmx:b-2bha7m) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/geometry/optimization/test/iris_test.cc#L385)):*
> ```cpp
> 
> // Helper method for testing IrisInRationalConfigurationSpace from a urdf string.
> HPolyhedron IrisRationalFromUrdf(const std::string urdf,
> ```

BTW, better to use pass-by-reference here as `const std::string&`.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 85 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1fZ7p-NJhDuL1DPsI:-Mu1fZ7p-NJhDuL1DPsJ:b7rqs2f) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/multibody/rational_forward_kinematics/cspace_free_region.h#L85)):*
> ```objc
>  * rational is aᵀx + b - 1, otherwise it is -1 - aᵀx - b
>  */
>  //TODO: why does this have the other_side_link_polytope? Isn't the requirement
> ```

Remove this? As explained in the previous PR, this is for debugging and testing, used in `cspace_free_region_test.cc`.
___
*[sos_iris_certifier/pinball_rational.ipynb, line 284 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1haPiCzOuZNRzVsBF:-Mu1haPiCzOuZNRzVsBG:b-w3fz0c) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/pinball_rational.ipynb#L284)):*
> ```
>    "execution_count": 10,
>    "metadata": {},
>    "outputs": [
> ```

BTW, could you remove this output?
___
*[sos_iris_certifier/sos_iris_example_python.ipynb, line 157 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1iDJo-Esw1-6mAEGV:-Mu1iDJo-Esw1-6mAEGW:b5db0dj) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/sos_iris_example_python.ipynb#L157)):*
> ```
>     "scrolled": true
>    },
>    "outputs": [
> ```

btw, could you remove the output?
___
*[sos_iris_certifier/sos_iris_fused_iiwa_example.ipynb, line 179 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1igfqD6WNGVxqbKqk:-Mu1igfqD6WNGVxqbKql:bmh37qk) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/sos_iris_fused_iiwa_example.ipynb#L179)):*
> ```
>    "execution_count": 7,
>    "metadata": {},
>    "outputs": [
> ```

Ditto, could you remove the output?
___
*[sos_iris_certifier/visualizations_utils.py, line 211 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1izJy1Cq9TfPf1ea6:-Mu1izJy1Cq9TfPf1ea7:btkixz1) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/visualizations_utils.py#L211)):*
> ```Python
> def plot_3d_poly(region, vis, name, mat = None, verbose = False):
> 
>     def prune_halfspaces(C, d):
> ```

BTW, why not to use the new ReduceInequalities function in HPolyhedron?
___
*[sos_iris_certifier/visualizations_utils.py, line 249 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1lLTy1quv6WXv2IyJ:-Mu1lLTy1quv6WXv2IyK:bcck25c) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/visualizations_utils.py#L249)):*
> ```Python
>     region = HPolyhedron(A_new, b_new)
> 
>     def project_and_triangulate(pts):
> ```

BTW, could you document that pts need to be co-planar? It took me a while to understand why only consider the normal from the first 3 points instead of all the points.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 85 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1fZ7p-NJhDuL1DPsI:-MuBH-rT09dcOdcyXMSO:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/multibody/rational_forward_kinematics/cspace_free_region.h#L85)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Remove this? As explained in the previous PR, this is for debugging and testing, used in `cspace_free_region_test.cc`.
</blockquote></details>

Done.
___
*[sos_iris_certifier/sos_iris_fused_iiwa_example.ipynb, line 179 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1igfqD6WNGVxqbKqk:-MuBHydD2_hEC-VWsDhv:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/sos_iris_fused_iiwa_example.ipynb#L179)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto, could you remove the output?
</blockquote></details>

Done.
___
*[sos_iris_certifier/visualizations_utils.py, line 249 at r3](https://reviewable.io/reviews/alexandreamice/drake/17#-Mu1lLTy1quv6WXv2IyJ:-MuBIUIGDfO8jOxil7q9:b-6twkhy) ([raw file](https://github.com/alexandreamice/drake/blob/bd52c430b88c59b24a5f3292ed86b0eb14d0c03d/sos_iris_certifier/visualizations_utils.py#L249)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, could you document that pts need to be co-planar? It took me a while to understand why only consider the normal from the first 3 points instead of all the points.
</blockquote></details>

@wernerpe @annan-zhang

**Review by hongkai-dai — COMMENTED** [review]
> Reviewed 2 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)* status: 22 of 30 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)* status: 0 of 443 files reviewed, 10 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 149 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1pddd7vpT9Y9j8nkW:-Mv1pddd7vpT9Y9j8nkX:bqcq0b9) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L149)):*
> ```cpp
> //      .def_readonly("a", &SeparatingPlane::a, doc.SeparatingPlane.a.doc)
>       .def("a",
>                     [](const SeparatingPlane* self){
> ```

Why using lambda function here? I would think that def_readonly should work?
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 526 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1qHmc1T6h67NYt40H:-Mv1qHmc1T6h67NYt40I:btdh5gv) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L526)):*
> ```objc
>    * t_lower <= t <= t_upper}.
>    */
>   void CspacePolytopeBisectionSearchVector(
> ```

This function is ver ysimilar to CspacePolytopeBinary Search. In the cc file, it also duplicates a lot of the code. This code duplication makes it hard to maintain in the future. I will say we should combine these two functions together. 
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 559 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1vM712rtSsOUYFzZq:-Mv1vM712rtSsOUYFzZr:bnyazsp) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L559)):*
> ```objc
>     * @return
>     */
>     void DoCspaceFreeRegionSearch(
> ```

We have many overloaded functions of DoCspaceFreeRegionSearch. Could you document what's their difference? And I would vote for removing these overloaded function as much as possible.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 628 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1v-pE5Oa8pwgHZPwV:-Mv1v-pF6bUpX_gANc_D:b-cvkopf) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L628)):*
> ```objc
>         Eigen::VectorXd* d_final) const;
> 
>     void DoCspaceFreeRegionSearchMultiSeed(
> ```

Do we really need this function? I think we can just call DoCspaceFreeRegionSearch in a for loop?
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 66 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1rB_n8-Us8p6Ln0ly:-Mv1rB_n8-Us8p6Ln0lz:b-c0pgdi) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L66)):*
> ```cpp
>     const auto t_halfchain = rational_forward_kinematics.FindTOnPath(
>         rational.link_polytope->body_index(), rational.expressed_body_index);
>     if (t_halfchain.rows() > 0) {
> ```

I think this change has been included in the previous PR? Not sure why it shows up again.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1542 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1uFrf0wWM7EevAtfI:-Mv1uFrf0wWM7EevAtfJ:b-1txgm1) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L1542)):*
> ```cpp
> 
>       // grow eps_max a little
>       eps_max = eps_max_const.cwiseMin(eps_max + scale*eps_max.cwiseAbs());
> ```

I am not convinced that this will always work. As far as I understand it, you want to make sure that eps_max(i) >= eps_min(i) fore each i. Aftwer taking this minimization I am not sure if that is still satisfied.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1591 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1wSZK9mCfiSCVrZhn:-Mv1wSZK9mCfiSCVrZho:b-mtal1c) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L1591)):*
> ```cpp
> }
> 
> void CspaceFreeRegion::DoCspaceFreeRegionSearch(
> ```

This function doesn't do much other than calling InterleavedCspacePolytopeSearch. I would vote for removing this function.

And since it constructs CspaceFreeRegion inside it, I would say this isn't a good design. (To call this function you need to construct a CspaceFreeRegion, but the constructed CspaceFreeRegion isn't used, as a new CspaceFreeRegion is constructed within this method).
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2174 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1x_Ps0dEe1R7siMRk:-Mv1x_Ps0dEe1R7siMRl:bey2g2u) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2174)):*
> ```cpp
>   }
>   // minimize epsilon.
>   prog.AddLinearCost(Eigen::MatrixXd::Ones(epsilon.rows(), 1), 0, epsilon);
> ```

Why choosing this particular cost? 
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2192 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1xunbArvRFqQbWRHK:-Mv1xunbArvRFqQbWRHL:b-wtito) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2192)):*
> ```cpp
> 
>   const double inflation_coeff = 1.1;
>   geometry::optimization::HPolyhedron Poly_lim_t =
> ```

Should check if t_lower <= 0 for each entry, otherwise this is not an inflation. So add
```cc
DRAKE_DEMAND((t_lower.array() <= 0).all());
DRAKE_DEMAND((t_upper.array() >= 0).all());
```
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2234 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1yUUo3uC8Mxo26HOw:-Mv1yUUo3uC8Mxo26HOx:b-gaukh1) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2234)):*
> ```cpp
>   };
> 
>   Eigen::VectorXd eps_max(C.rows());
> ```

Do you want to find eps(i) such that C.row(i) * t <= d(i) + eps(i) is redundant under t_lower <= t <= t_upper? If so I believe you can compute that directly through `ComputeMaxD` function wich computes this eps in the closed form.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)* status: 0 of 443 files reviewed, 10 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 149 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1pddd7vpT9Y9j8nkW:-Mv45Bps8uivGERyp-Lr:b-iudogv) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L149)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why using lambda function here? I would think that def_readonly should work?
</blockquote></details>

If you use def_readonly an attempt is made to cast the drake vector into a numpy array of dtype = object. The copy is done by reference which numpy rejects as it requires a copy by value. This is the quickest fix I found for this issue.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 526 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1qHmc1T6h67NYt40H:-Mv45UxgC5AzMZYTFifM:b-k3voa0) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L526)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This function is ver ysimilar to CspacePolytopeBinary Search. In the cc file, it also duplicates a lot of the code. This code duplication makes it hard to maintain in the future. I will say we should combine these two functions together. 
</blockquote></details>

I agree. I was doing this for prototyping purposes.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 628 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1v-pE5Oa8pwgHZPwV:-Mv45a3F3pMhCuw2J7nO:bnoypv4) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L628)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do we really need this function? I think we can just call DoCspaceFreeRegionSearch in a for loop?
</blockquote></details>

This wiil be an async call to parallelize this DoCspaceFreeRegionSearch
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 66 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1rB_n8-Us8p6Ln0ly:-Mv45rmz2qJkgOvU5uUM:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L66)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think this change has been included in the previous PR? Not sure why it shows up again.
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1542 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1uFrf0wWM7EevAtfI:-Mv47ayE9zAYtyHpLQrS:btp0p5k) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L1542)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I am not convinced that this will always work. As far as I understand it, you want to make sure that eps_max(i) >= eps_min(i) fore each i. Aftwer taking this minimization I am not sure if that is still satisfied.
</blockquote></details>

You are correct
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 1591 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1wSZK9mCfiSCVrZhn:-Mv49S8q4ixySSg0HdBb:b-u5jarf) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L1591)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This function doesn't do much other than calling InterleavedCspacePolytopeSearch. I would vote for removing this function.

And since it constructs CspaceFreeRegion inside it, I would say this isn't a good design. (To call this function you need to construct a CspaceFreeRegion, but the constructed CspaceFreeRegion isn't used, as a new CspaceFreeRegion is constructed within this method).
</blockquote></details>

Good point. I will make a separate file to call this from for parallel calls.
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2174 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1x_Ps0dEe1R7siMRk:-Mv49ZVx2IqlfK6-rFOa:b-4c4mci) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2174)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why choosing this particular cost? 
</blockquote></details>

Originally, when i was only searching for smallest shrinkage, epsilon was always positive and so this was the L1 norm. As the best I could hope for was that Epsilon go to 0 this helped encourage sparisity in my solution. This is no longer true but I did not change the cost
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2192 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1xunbArvRFqQbWRHK:-Mv4B9Zs2q31E4HAzbsj:b-886gsx) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2192)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Should check if t_lower <= 0 for each entry, otherwise this is not an inflation. So add
```cc
DRAKE_DEMAND((t_lower.array() <= 0).all());
DRAKE_DEMAND((t_upper.array() >= 0).all());
```
</blockquote></details>

Fixed
___
*[multibody/rational_forward_kinematics/cspace_free_region.cc, line 2234 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1yUUo3uC8Mxo26HOw:-Mv4Bpim-166h1oK16re:b-lvh5gv) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.cc#L2234)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you want to find eps(i) such that C.row(i) * t <= d(i) + eps(i) is redundant under t_lower <= t <= t_upper? If so I believe you can compute that directly through `ComputeMaxD` function wich computes this eps in the closed form.
</blockquote></details>

Thank you. I will change

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/17)* status: 0 of 443 files reviewed, 10 unresolved discussions (waiting on @hongkai-dai)

___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 559 at r15](https://reviewable.io/reviews/alexandreamice/drake/17#-Mv1vM712rtSsOUYFzZq:-Mv4DVED8pnln2CWRlYk:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/87ad108fe01c457b4e38383a6c0b8801508e4601/multibody/rational_forward_kinematics/cspace_free_region.h#L559)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

We have many overloaded functions of DoCspaceFreeRegionSearch. Could you document what's their difference? And I would vote for removing these overloaded function as much as possible.
</blockquote></details>

Done.

**Pull request closed without merging**
