### PR TITLE
C iris certify line fix for long substitution times.

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/56)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai for review. Thanks!

@wernerpe this might make visibility searches viable now on real plants.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/56#-:-NA_SVts6gyV5hTtX759:b50kexa)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/56#-:-NAa_aI1B9X6OeZEaoqM:bg7igkv)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 301 at r2](https://reviewable.io/reviews/alexandreamice/drake/56#-NAaZfuf0Y22WgnWYtfe:-NAaZfuf0Y22WgnWYtff:b-fqlqp9) ([raw file](https://github.com/alexandreamice/drake/blob/0723458b8118d7618e046a924ab41fb30c35bc99/multibody/rational_forward_kinematics/cspace_free_line.cc#L301)):*
> ```cpp
>     const std::unordered_map<symbolic::Variable, symbolic::Expression>&
>         t_to_line_subs,
>     std::unordered_map<symbolic::Monomial, symbolic::Polynomial>&
> ```

Google style guide requires using pointer for mutable input. So this should be `std::unordered_map<symbolic::Monomial, symbolic::Polynomial>*`

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/56)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`multibody/rational_forward_kinematics/cspace_free_line.cc` line 301 at r2](https://reviewable.io/reviews/alexandreamice/drake/56#-NAaZfuf0Y22WgnWYtfe:-NAdtHq5C84vibzaAVkF:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/0723458b8118d7618e046a924ab41fb30c35bc99/multibody/rational_forward_kinematics/cspace_free_line.cc#L301)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Google style guide requires using pointer for mutable input. So this should be `std::unordered_map<symbolic::Monomial, symbolic::Polynomial>*`
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
