### PR TITLE
Add the constraint that some points or polytope should be contained 

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/18)

### CODE REVIEW

**Review by hongkai-dai — COMMENTED** [review]
+@alexandreamice for review please, thanks!

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/18#-:-Mu-dHD_6WKnEPrZ8PTJ:b-kengf8)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Review by AlexandreAmice — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/18)* status: all files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 374 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBNyDVDUlEqIwnQoU7:-MuBNyDVDUlEqIwnQoU8:brq5l5o) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L374)):*
> ```cpp
>           py::arg("C_init"), py::arg("d_init"),
>           py::arg("bilinear_alternation_option"), py::arg("solver_options"),
>           py::arg("q_inner_pts"), py::arg("inner_polytope"),
> ```

When we have std::optional arguments should we provide default arguements q_inner_pts = None and inner_polytope = None so that the user doesn't need to specify these explicitly if they don't use them?
___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 398 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBOHkY3FR_OC0OKtA5:-MuBOHkY3FR_OC0OKtA6:b-89a4l7) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L398)):*
> ```cpp
>           py::arg("d_init"), py::arg("binary_search_option"),
>           py::arg("solver_options"), py::arg("q_inner_pts"),
>           py::arg("inner_polytope"),
> ```

Ditto
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 655 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBOotp4jTfpPVMe0Pl:-MuBOotp4jTfpPVMe0Pm:bo9tdxe) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/multibody/rational_forward_kinematics/cspace_free_region.h#L655)):*
> ```objc
>     const std::optional<std::pair<Eigen::MatrixXd, Eigen::VectorXd>>&
>         inner_polytope);
> ```

Could you add a TODO for me to implement that epsilon be a vector for which we can search each component independently?

**Review by hongkai-dai — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/18)* status: all files reviewed, 3 unresolved discussions (waiting on @AlexandreAmice)

___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 374 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBNyDVDUlEqIwnQoU7:-MuCYhiW-foAfZeyIbm_:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L374)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

When we have std::optional arguments should we provide default arguements q_inner_pts = None and inner_polytope = None so that the user doesn't need to specify these explicitly if they don't use them?
</blockquote></details>

Done.
___
*[bindings/pydrake/multibody/rational_forward_kinematics_py.cc, line 398 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBOHkY3FR_OC0OKtA5:-MuCYrRh97HnaIIMLSP1:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/bindings/pydrake/multibody/rational_forward_kinematics_py.cc#L398)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[multibody/rational_forward_kinematics/cspace_free_region.h, line 655 at r1](https://reviewable.io/reviews/alexandreamice/drake/18#-MuBOotp4jTfpPVMe0Pl:-MuCZ6zw8nBePA8MPZof:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/f116c7022043c658577ef1078ec1e8aa90ea37f2/multibody/rational_forward_kinematics/cspace_free_region.h#L655)):*
<details><summary><i>Previously, AlexandreAmice (Alexandre Amice) wrote…</i></summary><blockquote>

Could you add a TODO for me to implement that epsilon be a vector for which we can search each component independently?
</blockquote></details>

Done.

**Review by AlexandreAmice — APPROVED** [review]
:lgtm: 

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/18#-:-MuCrZhL4zGD3T0Ivd8w:b593w57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hongkai-dai)

**Pull request merged**
