### PR TITLE
IrisInRationalSpace

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This will add methods to be able to run Iris in rational space using Russ' SNOPT based approach.

---
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)

### CODE REVIEW

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
Checkpoint.

> Reviewed 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42#-:-N04F4JR8ZSfS5lpjiXj:by96gdd)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/iris.h, line 108 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04BJte7-yaJcPfe1Km:-N04BJte7-yaJcPfe1Kn:bt311dl) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L108)):*
> ```objc
>   SamePointConstraint(const MultibodyPlant<double>* plant,
>                       const Context<double>& context)
>       : solvers::Constraint(3, plant ? plant->num_positions() + 6 : 0,
> ```

It's strange that the constraint can take 0 variables. You have `DRAKE_DEMAND(plant_ != nullptr)` in a few lines below, so I don't think the check `plant ?` can be false.
___
*[geometry/optimization/iris.h, line 111 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04AQ7o32FInDNEX_l4:-N04AQ7o32FInDNEX_l5:b-wbi7z1) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L111)):*
> ```objc
>                             Vector3d::Zero(), Vector3d::Zero()),
>         plant_(plant),
>         context_(plant->CreateDefaultContext()) {
> ```

Why not to copy context directly? Then you can have multiple kinematic constraints sharing the same context, and hence same the kinematic computation across multiple kinematic constraints (context caches the kinematic computation result, for example the relative transform from a child link to its parent link). You could refer to https://github.com/RobotLocomotion/drake/blob/4e1146e7251aaff1e263b3b10a41f915827d9acb/multibody/inverse_kinematics/position_constraint.cc#L35 as an example.
___
*[geometry/optimization/iris.h, line 175 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04Cp7_8ptzGIdTTbKO:-N04Cp7a-DO2rsof88ik:b-ccf23j) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L175)):*
> ```objc
>     // Now add it the dydq terms.  We don't use the standard autodiff tools
>     // because these only impact a subset of the autodiff derivatives.
>     for (int i = 0; i < 3; i++) {
> ```

I am sorry, I don't think the math here is correct. I think here you suppose that the y[i].derivatives() should store the gradient w.r.t q, but that doesn't have to be the case. It is possible that x.derivatives() stores gradient w.r.t some arbitrary variable (for example the length of the robot link), and hence y.derivatives() should also store the gradient with that variable, not neccessaily w.r.t q.

I think the math is like this
```
y = p_WA - p_WB
dy/dq = Jq_v_WA - Jq_v_WB
dy/dp_AA = R_WA
dy/dp_BB = -R_WB
```
So if we denote the variable we take derivative as `z`, namely x.derivatives() stores dx/dz, then to compute dy/dz, we use the chain rule as
```
dy/dz = dy/dx * dx/dz
```
where `dy/dx = [dy/dq dy/dp_AA, dy/dp_BB]`.

Hence the code would be
```cc
Eigen::MatrixXd dy_dx(3, nq + 6);
dy_dx << Jq_v_WA - Jq_v_WB, R_WA, -R_WB;
Eigen::MatrixXd dy_dz = dy_dx * ExtractGradient(x);
*y = InitializeAutoDiffGivenGradient(p_WA - p_WB, dy_dz);
```
___
*[geometry/optimization/iris.h, line 282 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04F-qU6TbDddZPtJ5e:-N04F-qU6TbDddZPtJ5f:bmqrga9) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L282)):*
> ```objc
>     // because these only impact a subset of the autodiff derivatives.
>     for (int i = 0; i < 3; i++) {
>       (*y)[i].derivatives().head(plant_->num_positions()) +=
> ```

Ditto on gradient computation.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @AlexandreAmice and @hongkai-dai)

___
*[geometry/optimization/iris.h, line 175 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04Cp7_8ptzGIdTTbKO:-N04JJR4AGOjlyL5ImhV:bs5ietx) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L175)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't think the math here is correct. I think here you suppose that the y[i].derivatives() should store the gradient w.r.t q, but that doesn't have to be the case. It is possible that x.derivatives() stores gradient w.r.t some arbitrary variable (for example the length of the robot link), and hence y.derivatives() should also store the gradient with that variable, not neccessaily w.r.t q.

I think the math is like this
```
y = p_WA - p_WB
dy/dq = Jq_v_WA - Jq_v_WB
dy/dp_AA = R_WA
dy/dp_BB = -R_WB
```
So if we denote the variable we take derivative as `z`, namely x.derivatives() stores dx/dz, then to compute dy/dz, we use the chain rule as
```
dy/dz = dy/dx * dx/dz
```
where `dy/dx = [dy/dq dy/dp_AA, dy/dp_BB]`.

Hence the code would be
```cc
Eigen::MatrixXd dy_dx(3, nq + 6);
dy_dx << Jq_v_WA - Jq_v_WB, R_WA, -R_WB;
Eigen::MatrixXd dy_dz = dy_dx * ExtractGradient(x);
*y = InitializeAutoDiffGivenGradient(p_WA - p_WB, dy_dz);
```
</blockquote></details>

Sorry for being picky on this one. Normally we the derivatives in x is identity, meaning z = x and we just compute dy/dx, but our API allows to use a non-identity derivative in x hence we need to handle such unusual case.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)* status: 2 of 14 files reviewed, 4 unresolved discussions (waiting on @hongkai-dai)

___
*[`geometry/optimization/iris.h` line 108 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04BJte7-yaJcPfe1Km:-N0Xq6kwCfqaby5iSlrV:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L108)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It's strange that the constraint can take 0 variables. You have `DRAKE_DEMAND(plant_ != nullptr)` in a few lines below, so I don't think the check `plant ?` can be false.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.h` line 111 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04AQ7o32FInDNEX_l4:-N0Xq6z24R8cuJL-Vhl5:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L111)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why not to copy context directly? Then you can have multiple kinematic constraints sharing the same context, and hence same the kinematic computation across multiple kinematic constraints (context caches the kinematic computation result, for example the relative transform from a child link to its parent link). You could refer to https://github.com/RobotLocomotion/drake/blob/4e1146e7251aaff1e263b3b10a41f915827d9acb/multibody/inverse_kinematics/position_constraint.cc#L35 as an example.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.h` line 175 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04Cp7_8ptzGIdTTbKO:-N0Xq2LO0ymiBu6nTVXA:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L175)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Sorry for being picky on this one. Normally we the derivatives in x is identity, meaning z = x and we just compute dy/dx, but our API allows to use a non-identity derivative in x hence we need to handle such unusual case.
</blockquote></details>

Done.
___
*[`geometry/optimization/iris.h` line 282 at r2](https://reviewable.io/reviews/alexandreamice/drake/42#-N04F-qU6TbDddZPtJ5e:-N0Xq2903KLzn-LILEYd:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/1c5d28d5126ca509b0d2056c5fa4644df57bd404/geometry/optimization/iris.h#L282)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Ditto on gradient computation.
</blockquote></details>

Done.

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 9 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @AlexandreAmice)

___
*[`geometry/optimization/iris.h` line 150 at r3](https://reviewable.io/reviews/alexandreamice/drake/42#-N0aoCaE7bADipkpymHi:-N0aoCaF-MRHlKcMtqHI:bpqwgmb) ([raw file](https://github.com/alexandreamice/drake/blob/78c018354bde0660529b43e7f4e2dd1176ea7699/geometry/optimization/iris.h#L150)):*
> ```objc
>   // p_WA = X_WA(q)*p_AA
>   // dp_WA = Jq_v_WA*dq + X_WA(q)*dp_AA
>   void DoEval(const Eigen::Ref<const AutoDiffVecXd>& x,
> ```

Out of curiosity, why this function definition is in header file instead of in `iris.cc` file? Typically in C++ we declare the function in the header and define the function in the `.cc` file. Putting the function in the header file makes compilation slow (during compilation the code in the header file is inserted to every file that includes that header file).

Same for all DoEval function in this class and for SamePointConstraintRational class.

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai)

___
*[`geometry/optimization/iris.h` line 150 at r3](https://reviewable.io/reviews/alexandreamice/drake/42#-N0aoCaE7bADipkpymHi:-N0fdcSi5KtTX7rEWLjs:b-896fix) ([raw file](https://github.com/alexandreamice/drake/blob/78c018354bde0660529b43e7f4e2dd1176ea7699/geometry/optimization/iris.h#L150)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Out of curiosity, why this function definition is in header file instead of in `iris.cc` file? Typically in C++ we declare the function in the header and define the function in the `.cc` file. Putting the function in the header file makes compilation slow (during compilation the code in the header file is inserted to every file that includes that header file).

Same for all DoEval function in this class and for SamePointConstraintRational class.
</blockquote></details>

Done.

**Review by hongkai-dai — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42#-:-N0kpD-B2JxGJHLxpX71:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @AlexandreAmice)

**Review by hongkai-dai — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlexandreAmice)

**Pull request merged**
