### PR TITLE
C iris pinball iiwa example

### PR DESCRIPTION
**Pull request by AlexandreAmice**
This change is [Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47)

### CODE REVIEW

**Review by AlexandreAmice — COMMENTED** [review]
+@hongkai-dai +@wernerpe  for feature review.

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47#-:-N2mkDnmAU-JmsCJJ8Z-:b-sstuno)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @hongkai-dai and @wernerpe)

**Review by hongkai-dai — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @AlexandreAmice and @wernerpe)

___
*[`C_Iris_Examples/visualizations_utils.py` line 43 at r1](https://reviewable.io/reviews/alexandreamice/drake/47#-N2ruE0yCtNUqYkVeRCZ:-N2ruE0yCtNUqYkVeRC_:b-6hnpvk) ([raw file](https://github.com/alexandreamice/drake/blob/5bdc409924a54800477aba73650d8396fc8474fe/C_Iris_Examples/visualizations_utils.py#L43)):*
> ```Python
> 
> def n_colors_random(n=33):
>     colors = n_colors(100 * n)
> ```

Curious why multiplies by 100 here? Now the input to `n_colors` is 3300, different from the default input of `n_colors` (which is 33).

**Review by AlexandreAmice — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @hongkai-dai and @wernerpe)

___
*[`C_Iris_Examples/visualizations_utils.py` line 43 at r1](https://reviewable.io/reviews/alexandreamice/drake/47#-N2ruE0yCtNUqYkVeRCZ:-N2vDsYZ2TPOG29n2rTt:b-oi0sjf) ([raw file](https://github.com/alexandreamice/drake/blob/5bdc409924a54800477aba73650d8396fc8474fe/C_Iris_Examples/visualizations_utils.py#L43)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Curious why multiplies by 100 here? Now the input to `n_colors` is 3300, different from the default input of `n_colors` (which is 33).
</blockquote></details>

The idea is roughly to produce many colors and then randomly sample from the large list. I changed the sampling function as the shuffle is actually a really bad idea.

**Review by hongkai-dai — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47#-:-N2wWVlW-KcFkHSI_pHk:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wernerpe)

**Review by wernerpe — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47#-:-N3aAX7g1O_EH1oZCZwb:bks4kj3)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @wernerpe)

**Review by AlexandreAmice — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/alexandreamice/drake/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wernerpe)

**Pull request merged**
